export const COUNTRY_REQUEST_INITIATED = 'COUNTRY_REQUEST_INITIATED';
export const COUNTRY_REQUEST_SUCCESS = 'COUNTRY_REQUEST_SUCCESS';
export const COUNTRY_REQUEST_FAILED = 'COUNTRY_REQUEST_FAILED';
